name: build & deploy

on:
  push:
    branches: ['master']

env:
  project: aliyun-rest
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"

      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--ignore-platform-reqs -n --no-dev --no-progress --optimize-autoloader"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to aliyun
        uses: aliyun/acr-login@v1
        with:
          login-server: 'registry.cn-shanghai.aliyuncs.com'
          username: 'docloud'
          password: '${{ secrets.REGISTRY_PASSWORD }}'

      - name: build & push to aliyun
        run: |
          docker build -t registry.cn-shanghai.aliyuncs.com/dysh/mirror:${{ env.project }} .
          docker push registry.cn-shanghai.aliyuncs.com/dysh/mirror:${{ env.project }}
